title: Service
type: object
description: 'describes a telegraf instance we want to be running, maps 1:1 with k8s services, which should typically be backed by one pod. '
properties:
  id:
    type: integer
  name:
    type: string
  orgID:
    type: string
  datasourceID:
    type: integer
  nextFreePort:
    type: integer
    description: keeps track of what ports are available to assign. incremented atomically
required:
  - name
  - orgID
