  type: object
  properties:
    bucket:
      type: string
      description: name of non system bucket
    retentionPeriodSeconds:
      type: integer
      description: retention period of non system bucket
    limit:
      $ref: "../../quartz/schemas/OrgLimits.yml"
