openapi: 3.0.0
info:
  title: fluxdocsd
  version: 1.0.0
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /
paths:
  /fluxdocs:
    get:
      summary: get all records
      operationId: getAllFluxdocs
      responses:
        '200':
          description: all records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FluxdocsArray'
        '401':
          $ref: '#/components/responses/ServerError'
        '500':
          $ref: '#/components/responses/ServerError'
  '/fluxdocs/{id}':
    get:
      summary: get single record by its ID
      operationId: getFluxdoc
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: returns the record
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fluxdocs'
        '400':
          $ref: '#/components/responses/ServerError'
        '401':
          $ref: '#/components/responses/ServerError'
        '500':
          $ref: '#/components/responses/ServerError'
  '/fluxdocs/search/{searchTerm}':
    get:
      summary: get all records that contain name
      operationId: getFluxdocsSearch
      parameters:
        - name: searchTerm
          in: path
          schema:
            type: string
          required: true
        - name: field
          in: query
          schema:
            type: string
          required: false
      responses:
        '200':
          description: returns all matching records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FluxdocsArray'
        '400':
          $ref: '#/components/responses/ServerError'
        '401':
          $ref: '#/components/responses/ServerError'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  requestBodies:
    FluxdocsParams:
      description: Fluxdocs record
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Fluxdocs'
  schemas:
    Fluxdocs:
      required:
        - path
        - package
        - name
        - kind
        - headline
        - fluxType
      properties:
        path:
          type: string
        package:
          type: string
        name:
          type: string
        kind:
          type: string
        headline:
          type: string
        fluxType:
          type: string
        description:
          type: string
        fluxParameters:
          type: array
          items:
            $ref: '#/components/schemas/FluxdocsParameters'
    FluxdocsArray:
      type: array
      items:
        $ref: '#/components/schemas/Fluxdocs'
    FluxdocsParameters:
      required:
        - headline
        - name
        - required
      properties:
        description:
          type: string
        headline:
          type: string
        name:
          type: string
        required:
          type: boolean
    Error:
      properties:
        code:
          description: code is the machine-readable error code.
          readOnly: true
          type: string
          enum:
            - internal error
            - not found
            - conflict
            - invalid
            - unprocessable entity
            - empty value
            - unavailable
            - forbidden
            - too many requests
            - unauthorized
            - method not allowed
            - request too large
            - unsupported media type
        message:
          readOnly: true
          description: Human-readable message.
          type: string
        op:
          readOnly: true
          description: Describes the logical code operation when the error occurred. Useful for debugging.
          type: string
        err:
          readOnly: true
          description: Stack of errors that occurred during processing of the request. Useful for debugging.
          type: string
      required:
        - code
  responses:
    NoContent:
      description: No content
    ServerError:
      description: Non 2XX error response from server.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
