openapi: 3.0.0
info:
  title: Complete InfluxDB OSS API
servers:
- url: ""
paths:
  /api/v2/maps/mapToken:
    get:
      operationId: getMapboxToken
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
          description: A temp token for Mapbox
        "401":
          $ref: '#/components/responses/ServerError'
        "500":
          $ref: '#/components/responses/ServerError'
        default:
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    Error:
      properties:
        code:
          description: code is the machine-readable error code.
          enum:
          - internal error
          - not found
          - conflict
          - invalid
          - unprocessable entity
          - empty value
          - unavailable
          - forbidden
          - too many requests
          - unauthorized
          - method not allowed
          - request too large
          - unsupported media type
          readOnly: true
          type: string
        err:
          description: err is a stack of errors that occurred during processing of
            the request. Useful for debugging.
          readOnly: true
          type: string
        message:
          description: message is a human-readable message.
          readOnly: true
          type: string
        op:
          description: op describes the logical code operation during error. Useful
            for debugging.
          readOnly: true
          type: string
      required:
      - code
      - message
    Token:
      properties:
        token:
          type: string
      type: object
  responses:
    ServerError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Non 2XX error response from server.
