version: 2.1
jobs:
  build:
    docker:
      - image: "quay.io/influxdb/oats"
    steps:
      - run:
          name: Ensure oats compatibility
          command: sh /src/openapi/scripts/test-oats.sh
  generateTest:
    docker:
      - image: "quay.io/influxdb/swagger-cli"
    steps:
      - run:
          name: Ensure compiled contracts match
          command: sh /openapi/scripts/test.sh
