version: 2.1
jobs:
  test-oats:
    docker:
      - image: "quay.io/influxdb/oats-ci"
    steps:
      - checkout
      - run:
          name: Ensure oats compatibility
          command: sh /root/project/scripts/test-oats.sh
          environment:
            CONTRACTS: '/root/project/contracts'
  test-contracts:
    docker:
      - image: "quay.io/influxdb/swagger-cli-ci"
    steps:
      - checkout
      - run:
          name: Ensure compiled contracts match
          command: sh /root/project/scripts/test.sh
  lint-yamls:
    docker:
      - image: "cimg/base:2021.04"
    steps:
      - checkout
      - run:
          name: trailing spaces
          command: "[ 0 -eq $(grep -rin ' $' $HOME/project/src/ | tee -a /dev/stderr | wc -l) ]"
      - run:
          name: missing ending newlines
          command: "find $HOME/project/src/ -type f | xargs -I {} bash -c 'tail -c 1 {} | read -r _ || (echo \"Missing newline at end of {}\"; false)'"
workflows:
  verify:
    jobs:
      - test-oats
      - test-contracts
      - lint-yamls
