version: 2.1
jobs:
  test-oats:
    docker:
      - image: "quay.io/influxdb/oats-ci"
    steps:
      - checkout
      - run:
          name: Ensure oats compatibility
          command: sh /root/project/scripts/test-oats.sh
          environment:
            CONTRACTS: '/root/project/contracts'
  test-contracts:
    docker:
      - image: "quay.io/influxdb/swagger-cli-ci"
    steps:
      - checkout
      - run:
          name: Ensure compiled contracts match
          command: sh /root/project/scripts/test.sh
  lint-yamls:
    docker:
      - image: "cimg/python:3.9"
    steps:
      - checkout
      - run:
          name: install yamllint
          command: pip install --user yamllint
      - run:
          name: run yamllint
          command: yamllint -d $HOME/project/.circleci/yamllint.conf $HOME/project/src/
workflows:
  verify:
    jobs:
      - test-oats
      - test-contracts
      - lint-yamls
