version: 2.1
jobs:
  build:
    working_directory: ~/openapi
    steps:
      - run:
          name: Ensure oats compatibility
          command: make test-oats
  generateTest:
    working_directory: ~/openapi
    steps:
      - run:
          name: Ensure compiled contracts match
          command: make test
