version: 2.1
jobs:
  test-oats:
    docker:
      - image: "quay.io/influxdb/oats-ci"
    steps:
      - checkout
      - run:
          name: Ensure oats compatibility
          command: sh /root/project/scripts/test-oats.sh
          environment:
            CONTRACTS: '/root/project/contracts'
  test-contracts:
    docker:
      - image: "quay.io/influxdb/swagger-cli-ci"
    steps:
      - checkout
      - run:
          name: Ensure compiled contracts match
          command: sh /root/project/scripts/test.sh
workflows:
  verify:
    jobs:
      - test-oats
      - test-contracts
