get:
  operationId: GetConfig
  tags:
    - Config
  summary: Get the run-time configuration of the instance
  parameters:
    - $ref: '../../common/parameters/TraceSpan.yml'
  responses:
    '200':
      description: Payload body contains the run-time configuration of the InfluxDB instance.
      content:
        application/json:
          schema:
            $ref: '../schemas/Config.yml'
    '401':
      $ref: '../../common/responses/ServerError.yml'
    default:
      $ref: '../../common/responses/ServerError.yml'
