get:
  operationId: GetConfig
  tags:
    - System information endpoints
  summary: Retrieve runtime configuration
  description: |
    Returns the active runtime configuration of the InfluxDB instance.

    In InfluxDB v2.2+, use this endpoint to view your active runtime configuration,
    including flags and environment variables.

    #### Related guides

    - [View your runtime server configuration]({{% INFLUXDB_DOCS_URL %}}/reference/config-options/#view-your-runtime-server-configuration)

  parameters:
    - $ref: '../../common/parameters/TraceSpan.yml'
  responses:
    '200':
      description: |
        Success.
        The response body contains the active runtime configuration of the InfluxDB instance.
      content:
        application/json:
          schema:
            $ref: '../schemas/Config.yml'
    '401':
      $ref: '../../common/responses/ServerError.yml'
    default:
      $ref: '../../common/responses/ServerError.yml'
