get:
  operationId: GetSettingsNotifications
  tags:
    - Settings
  responses:
    '200':
      description: Settings for billing notifications
      content:
        application/json:
          schema:
            $ref: '../schemas/BillingNotifySettings.yml'
    '401':
      description: Unauthorized
      $ref: '../../common/responses/Error.yml'
    '404':
      description: Notification Settings nil or User/Org not found
      $ref: '../../common/responses/Error.yml'
    '406':
      description: Not Acceptable
      $ref: '../../common/responses/Error.yml'
    default:
      description: Unexpected error
      $ref: '../../common/responses/Error.yml'
put:
  operationId: PutSettingsNotifications
  tags:
    - Settings
  requestBody:
    description: Update to notify setting
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/BillingNotifySettings.yml'
  responses:
    '200':
      description: billing notification settings updated
      content:
        application/json:
          schema:
            $ref: '../schemas/BillingNotifySettings.yml'
    '400':
      description: Bad Request
      $ref: '../../common/responses/Error.yml'
    '401':
      description: Unauthorized
      $ref: '../../common/responses/Error.yml'
    default:
      description: Unexpected error
      $ref: '../../common/responses/Error.yml'
