get:
  operationId: GetSettingsNotifications
  tags:
    - Settings
  responses:
    '200':
      description: Settings for billing notifications
      content:
        application/json:
          schema:
            $ref: '../schemas/BillingNotifySettings.yml'
    default:
      description: Unexpected error
      $ref: '../../common/responses/ServerError.yml'
put:
  operationId: PutSettingsNotifications
  tags:
    - Settings
  requestBody:
    description: Update to notify setting
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/BillingNotifySettings.yml'
  responses:
    '200':
      description: billing notification settings updated
      content:
        application/json:
          schema:
            $ref: '../schemas/BillingNotifySettings.yml'
    default:
      description: Unexpected error
      $ref: '../../common/responses/ServerError.yml'
