get:
  tags:
    - OAuth
  summary: Retrieve required OAuth client variables
  responses:
    '200':
      description: Required OAuth client variables
      content:
        application/json:
          schema:
            $ref: "../schemas/OAuthClientConfig.yml"
    default:
      description: unexpected error
      $ref: '../../common/responses/ServerError.yml'
