type: object
properties:
  params:
    type: object
    additionalProperties:
      type: string
      enum: ["any", "bool", "duration", "float", "int", "string", "time", "uint"]
    description: |
      The `params` keys and value type defined in the script.
