openapi: "3.0.0"
info:
  title: Subset of Influx API covered by Influx CLI
  version: 2.0.0
servers:
  - url: /api/v2
paths:
  /health:
    $ref: "./oss/paths/health.yml"
  /setup:
    $ref: "./common/paths/setup.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./common/parameters/TraceSpan.yml"
  schemas:
    Error:
      $ref: "./common/schemas/Error.yml"
    ErrorCode:
      $ref: "./common/schemas/ErrorCode.yml"
    HealthCheck:
      $ref: "./common/schemas/HealthCheck.yml"
    HealthCheckStatus:
      $ref: "./common/schemas/HealthCheckStatus.yml"
    OnboardingRequest:
      $ref: "./common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./common/schemas/OnboardingResponse.yml"
    UserResponse:
      $ref: "./common/schemas/UserResponse.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Organization:
      $ref: "./common/schemas/Organization.yml"
    Bucket:
      $ref: "./common/schemas/Bucket.yml"
    RetentionRules:
      $ref: "./common/schemas/RetentionRules.yml"
    RetentionRule:
      $ref: "./common/schemas/RetentionRule.yml"
    Labels:
      $ref: "./common/schemas/Labels.yml"
    Label:
      $ref: "./common/schemas/Label.yml"
    Authorization:
      $ref: "./common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./common/schemas/Permission.yml"
