openapi: "3.0.0"
info:
  title: Subset of Influx API covered by Influx CLI
  version: 2.0.0
servers:
  - url: /api/v2
paths:
  /health:
    servers:
      - url: ''
    $ref: "./oss/paths/health.yml"
  /setup:
    $ref: "./common/paths/setup.yml"
  /write:
    $ref: "./common/paths/write.yml"
  /buckets:
    $ref: "./common/paths/buckets.yml"
  /buckets/{bucketID}:
    $ref: "./common/paths/buckets_bucketID.yml"
  /orgs:
    $ref: "./common/paths/orgs.yml"
  /buckets/{bucketID}/schema/measurements:
    $ref: "./cloud/paths/measurements.yml"
  /buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: "./cloud/paths/measurements_measurementID.yml"
  /query:
    $ref: "./common/paths/query.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./common/parameters/TraceSpan.yml"
    Offset:
      $ref: "./common/parameters/Offset.yml"
    Limit:
      $ref: "./common/parameters/Limit.yml"
    After:
      $ref: "./common/parameters/After.yml"
    Descending:
      $ref: "./common/parameters/Descending.yml"
  schemas:
    Error:
      $ref: "./common/schemas/Error.yml"
    ErrorCode:
      $ref: "./common/schemas/ErrorCode.yml"
    HealthCheck:
      $ref: "./common/schemas/HealthCheck.yml"
    HealthCheckStatus:
      $ref: "./common/schemas/HealthCheckStatus.yml"
    OnboardingRequest:
      $ref: "./common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./common/schemas/OnboardingResponse.yml"
    UserResponse:
      $ref: "./common/schemas/UserResponse.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Organizations:
      $ref: "./common/schemas/Organizations.yml"
    Organization:
      $ref: "./common/schemas/Organization.yml"
    Buckets:
      $ref: "./common/schemas/Buckets.yml"
    Bucket:
      $ref: "./common/schemas/Bucket.yml"
    PostBucketRequest:
      $ref: "./common/schemas/PostBucketRequest.yml"
    RetentionRules:
      $ref: "./common/schemas/RetentionRules.yml"
    RetentionRule:
      $ref: "./common/schemas/RetentionRule.yml"
    PatchBucketRequest:
      $ref: "./common/schemas/PatchBucketRequest.yml"
    PatchRetentionRules:
      $ref: "./common/schemas/PatchRetentionRules.yml"
    PatchRetentionRule:
      $ref: "./common/schemas/PatchRetentionRule.yml"
    Labels:
      $ref: "./common/schemas/Labels.yml"
    Label:
      $ref: "./common/schemas/Label.yml"
    Authorization:
      $ref: "./common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./common/schemas/Permission.yml"
    WritePrecision:
      $ref: "./common/schemas/WritePrecision.yml"
    LineProtocolError:
      $ref: "./common/schemas/LineProtocolError.yml"
    LineProtocolLengthError:
      $ref: "./common/schemas/LineProtocolLengthError.yml"
    SchemaType:
      $ref: "./common/schemas/SchemaType.yml"
    ColumnDataType:
      $ref: "./cloud/schemas/ColumnDataType.yml"
    ColumnSemanticType:
      $ref: "./cloud/schemas/ColumnSemanticType.yml"
    MeasurementSchema:
      $ref: "./cloud/schemas/MeasurementSchema.yml"
    MeasurementSchemaColumn:
      $ref: "./cloud/schemas/MeasurementSchemaColumn.yml"
    MeasurementSchemaCreateRequest:
      $ref: "./cloud/schemas/MeasurementSchemaCreateRequest.yml"
    MeasurementSchemaList:
      $ref: "./cloud/schemas/MeasurementSchemaList.yml"
    MeasurementSchemaUpdateRequest:
      $ref: "./cloud/schemas/MeasurementSchemaUpdateRequest.yml"
    Query:
      $ref: "./common/schemas/Query.yml"
    File:
      $ref: "./common/schemas/File.yml"
    NodeType:
      $ref: "./common/schemas/NodeType.yml"
    PackageClause:
      $ref: "./common/schemas/PackageClause.yml"
    ImportDeclaration:
      $ref: "./common/schemas/ImportDeclaration.yml"
    Statement:
      $ref: "./common/schemas/Statement.yml"
    BadStatement:
      $ref: "./common/schemas/BadStatement.yml"
    VariableAssignment:
      $ref: "./common/schemas/VariableAssignment.yml"
    MemberAssignment:
      $ref: "./common/schemas/MemberAssignment.yml"
    ExpressionStatement:
      $ref: "./common/schemas/ExpressionStatement.yml"
    ReturnStatement:
      $ref: "./common/schemas/ReturnStatement.yml"
    OptionStatement:
      $ref: "./common/schemas/OptionStatement.yml"
    BuiltinStatement:
      $ref: "./common/schemas/BuiltinStatement.yml"
    TestStatement:
      $ref: "./common/schemas/TestStatement.yml"
    Identifier:
      $ref: "./common/schemas/Identifier.yml"
    Expression:
      $ref: "./common/schemas/Expression.yml"
    MemberExpression:
      $ref: "./common/schemas/MemberExpression.yml"
    ArrayExpression:
      $ref: "./common/schemas/ArrayExpression.yml"
    DictExpression:
      $ref: "./common/schemas/DictExpression.yml"
    DictItem:
      $ref: "./common/schemas/DictItem.yml"
    FunctionExpression:
      $ref: "./common/schemas/FunctionExpression.yml"
    BinaryExpression:
      $ref: "./common/schemas/BinaryExpression.yml"
    CallExpression:
      $ref: "./common/schemas/CallExpression.yml"
    ConditionalExpression:
      $ref: "./common/schemas/ConditionalExpression.yml"
    LogicalExpression:
      $ref: "./common/schemas/LogicalExpression.yml"
    IndexExpression:
      $ref: "./common/schemas/IndexExpression.yml"
    ObjectExpression:
      $ref: "./common/schemas/ObjectExpression.yml"
    ParenExpression:
      $ref: "./common/schemas/ParenExpression.yml"
    PipeExpression:
      $ref: "./common/schemas/PipeExpression.yml"
    UnaryExpression:
      $ref: "./common/schemas/UnaryExpression.yml"
    BooleanLiteral:
      $ref: "./common/schemas/BooleanLiteral.yml"
    DateTimeLiteral:
      $ref: "./common/schemas/DateTimeLiteral.yml"
    DurationLiteral:
      $ref: "./common/schemas/DurationLiteral.yml"
    FloatLiteral:
      $ref: "./common/schemas/FloatLiteral.yml"
    IntegerLiteral:
      $ref: "./common/schemas/IntegerLiteral.yml"
    PipeLiteral:
      $ref: "./common/schemas/PipeLiteral.yml"
    RegexpLiteral:
      $ref: "./common/schemas/RegexpLiteral.yml"
    StringLiteral:
      $ref: "./common/schemas/StringLiteral.yml"
    UnsignedIntegerLiteral:
      $ref: "./common/schemas/UnsignedIntegerLiteral.yml"
    PropertyKey:
      $ref: "./common/schemas/PropertyKey.yml"
    Property:
      $ref: "./common/schemas/Property.yml"
    Node:
      $ref: "./common/schemas/Node.yml"
    Block:
      $ref: "./common/schemas/Block.yml"
    Dialect:
      $ref: "./common/schemas/Dialect.yml"
    InfluxQLQuery:
      $ref: "./common/schemas/InfluxQLQuery.yml"
