openapi: "3.0.0"
info:
  title: Subset of Influx API covered by Influx CLI
  version: 2.0.0
servers:
  - url: /api/v2
paths:
  /health:
    servers:
      - url: ''
    $ref: "./oss/paths/health.yml"
  /setup:
    $ref: "./common/paths/setup.yml"
  /write:
    $ref: "./common/paths/write.yml"
  /buckets:
    $ref: "./common/paths/buckets.yml"
  /buckets/{bucketID}:
    $ref: "./common/paths/buckets_bucketID.yml"
  /orgs:
    $ref: "./common/paths/orgs.yml"
  /buckets/{bucketID}/schema/measurements:
    $ref: "./cloud/paths/measurements.yml"
  /buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: "./cloud/paths/measurements_measurementID.yml"
  /query:
    $ref: "./cli/paths/query.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./common/parameters/TraceSpan.yml"
    Offset:
      $ref: "./common/parameters/Offset.yml"
    Limit:
      $ref: "./common/parameters/Limit.yml"
    After:
      $ref: "./common/parameters/After.yml"
    Descending:
      $ref: "./common/parameters/Descending.yml"
  schemas:
    Error:
      $ref: "./common/schemas/Error.yml"
    ErrorCode:
      $ref: "./common/schemas/ErrorCode.yml"
    HealthCheck:
      $ref: "./common/schemas/HealthCheck.yml"
    HealthCheckStatus:
      $ref: "./common/schemas/HealthCheckStatus.yml"
    OnboardingRequest:
      $ref: "./common/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./common/schemas/OnboardingResponse.yml"
    UserResponse:
      $ref: "./common/schemas/UserResponse.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Organizations:
      $ref: "./common/schemas/Organizations.yml"
    Organization:
      $ref: "./common/schemas/Organization.yml"
    Buckets:
      $ref: "./common/schemas/Buckets.yml"
    Bucket:
      $ref: "./common/schemas/Bucket.yml"
    PostBucketRequest:
      $ref: "./common/schemas/PostBucketRequest.yml"
    RetentionRules:
      $ref: "./common/schemas/RetentionRules.yml"
    RetentionRule:
      $ref: "./common/schemas/RetentionRule.yml"
    PatchBucketRequest:
      $ref: "./common/schemas/PatchBucketRequest.yml"
    PatchRetentionRules:
      $ref: "./common/schemas/PatchRetentionRules.yml"
    PatchRetentionRule:
      $ref: "./common/schemas/PatchRetentionRule.yml"
    Labels:
      $ref: "./common/schemas/Labels.yml"
    Label:
      $ref: "./common/schemas/Label.yml"
    Authorization:
      $ref: "./common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./common/schemas/Permission.yml"
    WritePrecision:
      $ref: "./common/schemas/WritePrecision.yml"
    LineProtocolError:
      $ref: "./common/schemas/LineProtocolError.yml"
    LineProtocolLengthError:
      $ref: "./common/schemas/LineProtocolLengthError.yml"
    SchemaType:
      $ref: "./common/schemas/SchemaType.yml"
    ColumnDataType:
      $ref: "./cloud/schemas/ColumnDataType.yml"
    ColumnSemanticType:
      $ref: "./cloud/schemas/ColumnSemanticType.yml"
    MeasurementSchema:
      $ref: "./cloud/schemas/MeasurementSchema.yml"
    MeasurementSchemaColumn:
      $ref: "./cloud/schemas/MeasurementSchemaColumn.yml"
    MeasurementSchemaCreateRequest:
      $ref: "./cloud/schemas/MeasurementSchemaCreateRequest.yml"
    MeasurementSchemaList:
      $ref: "./cloud/schemas/MeasurementSchemaList.yml"
    MeasurementSchemaUpdateRequest:
      $ref: "./cloud/schemas/MeasurementSchemaUpdateRequest.yml"
    Query:
      $ref: "./cli/schemas/Query.yml"
    Dialect:
      $ref: "./common/schemas/Dialect.yml"
