openapi: '3.0.0'
info:
  title: InfluxDB Cloud API Service
  version: 2.0.1
  description: |
    The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /api/v2
#REF_CLOUD_TAGS
#REF_CLOUD_TAG_GROUPS
paths:
#REF_COMMON_PATHS
  /users:
    $ref: './cloud/paths/users.yml'
  '/users/{userID}':
    $ref: './cloud/paths/users_userID.yml'
  /setup:
    $ref: './cloud/paths/setup.yml'
  /setup/user:
    $ref: './cloud/paths/setup_user.yml'
  /variables:
    $ref: './cloud/paths/variables.yml'
  '/variables/{variableID}':
    $ref: './cloud/paths/variables_variableID.yml'
  /buckets/{bucketID}/schema/measurements:
    $ref: './cloud/paths/measurements.yml'
  /buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: './cloud/paths/measurements_measurementID.yml'
  /orgs/{orgID}/limits:
    $ref: './cloud/paths/orgs_orgID_limits_get.yml'
  /orgs/{orgID}/usage:
    $ref: './cloud/paths/orgs_orgID_usage.yml'
  /dashboards:
    $ref: './cloud/paths/dashboards.yml'
  /tasks:
    $ref: './cloud/paths/tasks.yml'
  /tasks/{taskID}:
    $ref: "./cloud/paths/tasks_taskID.yml"
components:
  parameters:
  #REF_COMMON_PARAMETERS
  schemas:
    #REF_COMMON_SCHEMAS
    User:
      $ref: './cloud/schemas/User.yml'
    Users:
      $ref: './cloud/schemas/Users.yml'
    OnboardingRequest:
      $ref: './cloud/schemas/OnboardingRequest.yml'
    OnboardingResponse:
      $ref: './cloud/schemas/OnboardingResponse.yml'
    Limit:
      $ref: './cloud/schemas/Limit.yml'
    Variable:
      $ref: './cloud/schemas/Variable.yml'
    Variables:
      $ref: './cloud/schemas/Variables.yml'
    ColumnDataType:
      $ref: './cloud/schemas/ColumnDataType.yml'
    ColumnSemanticType:
      $ref: './cloud/schemas/ColumnSemanticType.yml'
    MeasurementSchema:
      $ref: './cloud/schemas/MeasurementSchema.yml'
    MeasurementSchemaColumn:
      $ref: './cloud/schemas/MeasurementSchemaColumn.yml'
    MeasurementSchemaCreateRequest:
      $ref: './cloud/schemas/MeasurementSchemaCreateRequest.yml'
    MeasurementSchemaList:
      $ref: './cloud/schemas/MeasurementSchemaList.yml'
    MeasurementSchemaUpdateRequest:
      $ref: './cloud/schemas/MeasurementSchemaUpdateRequest.yml'
    Tasks:
      $ref: "./cloud/schemas/Tasks.yml"
    Task:
      $ref: "./cloud/schemas/Task.yml"
    TaskCreateRequest:
      $ref: "./cloud/schemas/TaskCreateRequest.yml"
    TaskScriptID:
      $ref: "./cloud/schemas/ScriptID.yml"
    TaskScriptParameters:
      $ref: "./cloud/schemas/ScriptParameters.yml"
    TaskUpdateRequest:
      $ref: "./cloud/schemas/TaskUpdateRequest.yml"
  responses:
    #REF_COMMON_RESPONSES
  examples:
    AuthorizationPostRequest:
      $ref: "./common/requestBody/examples/AuthorizationRequestExamples.yml#/AuthorizationPostRequest"
    AuthorizationWithResourcePostRequest:
      $ref: "./common/requestBody/examples/AuthorizationRequestExamples.yml#/AuthorizationWithResourcePostRequest"
    AuthorizationWithUserPostRequest:
      $ref: "./common/requestBody/examples/AuthorizationRequestExamples.yml#/AuthorizationWithUserPostRequest"
    TaskWithFluxRequest:
      $ref: "./common/requestBody/examples/TaskWithFluxRequest.yml"
    TaskWithScriptRequest:
      $ref: "./cloud/requestBody/examples/TaskWithScriptRequest.yml"
  securitySchemes:
    TokenAuthentication:
      type: apiKey
      name: Authorization
      in: header
      description: |
        Use the [Token authentication](#section/Authentication/TokenAuthentication)
        scheme to authenticate to the InfluxDB API.

        In your API requests, send an `Authorization` header.
        For the header value, provide the word `Token` followed by a space and an InfluxDB API token.
        The word `Token` is case-sensitive.

        ### Syntax

        `Authorization: Token INFLUX_API_TOKEN`

        ### Example

        #### Use Token authentication with cURL

        The following example shows how to use cURL to send an API request that uses Token authentication:

        ```sh
        curl --request GET "INFLUX_URL/api/v2/buckets" \
             --header "Authorization: Token INFLUX_API_TOKEN"
        ```

        Replace the following:

          - *`INFLUX_URL`*: your InfluxDB Cloud URL
          - *`INFLUX_API_TOKEN`*: your [InfluxDB API token]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#token)

        ### Related endpoints

        - [`/authorizations` endpoints](#tag/Authorizations-(API-tokens))

        ### Related guides

        - [Authorize API requests]({{% INFLUXDB_DOCS_URL %}}/api-guide/api_intro/#authentication)
        - [Manage API tokens]({{% INFLUXDB_DOCS_URL %}}/security/tokens/)
    BasicAuthentication:
      type: http
      scheme: basic
      description: |
        ### Basic authentication scheme

        Use the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:

        ### Syntax

        `Authorization: Basic BASE64_ENCODED_CREDENTIALS`

        To construct the `BASE64_ENCODED_CREDENTIALS`, combine the username and
        the password with a colon (`USERNAME:PASSWORD`), and then encode the
        resulting string in [base64](https://developer.mozilla.org/en-US/docs/Glossary/Base64).
        Many HTTP clients encode the credentials for you before sending the
        request.

        _**Warning**: Base64-encoding can easily be reversed to obtain the original
        username and password. It is used to keep the data intact and does not provide
        security. You should always use HTTPS when authenticating or sending a request with
        sensitive information._

        ### Examples

        In the examples, replace the following:

        - **`EMAIL_ADDRESS`**: InfluxDB Cloud username (the email address the user signed up with)
        - **`PASSWORD`**: InfluxDB Cloud [API token]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#token)
        - **`INFLUX_URL`**: your InfluxDB Cloud URL

        #### Encode credentials with cURL

        The following example shows how to use cURL to send an API request that uses Basic authentication.
        With the `--user` option, cURL encodes the credentials and passes them
        in the `Authorization: Basic` header.

        ```sh
        curl --get "INFLUX_URL/api/v2/signin"
            --user "EMAIL_ADDRESS":"PASSWORD"
        ```

        #### Encode credentials with Flux

        The Flux [`http.basicAuth()` function](https://docs.influxdata.com/flux/v0.x/stdlib/http/basicauth/) returns a Base64-encoded
        basic authentication header using a specified username and password combination.

        #### Encode credentials with JavaScript

        The following example shows how to use the JavaScript `btoa()` function
        to create a Base64-encoded string:

        ```js
        btoa('EMAIL_ADDRESS:PASSWORD')
        ```

        The output is the following:

        ```js
        'VVNFUk5BTUU6UEFTU1dPUkQ='
        ```

        Once you have the Base64-encoded credentials, you can pass them in the
        `Authorization` header--for example:

        ```sh
        curl --get "INFLUX_URL/api/v2/signin"
            --header "Authorization: Basic VVNFUk5BTUU6UEFTU1dPUkQ="
        ```

        To learn more about HTTP authentication, see
        [Mozilla Developer Network (MDN) Web Docs, HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)._
security:
  - TokenAuthentication: []
