openapi: '3.0.0'
info:
  title: IDPE-exclusive API endpoints
  version: 2.3.3
servers:
  - description: |-
      V2 Private is not necessarily private in the sense that the world cannot view it,
      but defines routes that are of little use to the world (quartz-specific routes that
      require a super token (`/setup/user`)), or routes that are not yet guaranteed to
      not change.
    url: /api/v2private
paths:
  /oauth/clientConfig:
    $ref: './cloud/paths/oauth_clientConfig.yml'
  /flags:
    $ref: './cloud/paths/flags.yml'
  /limitevents:
    $ref: './cloud/paths/limitevents.yml'
  /orgs/{orgID}/limits:
    $ref: './cloud/paths/orgs_orgID_limits.yml'
  /orgs/{orgID}/limits/status:
    $ref: './cloud/paths/orgs_orgID_limits_status.yml'
  /orgs/{orgID}/settings:
    $ref: './cloud/paths/orgs_orgID_settings.yml'
  /tenants:
    $ref: './cloud/paths/tenants.yml'
  /provision:
    $ref: './cloud/paths/provision.yml'
  /provision/user:
    $ref: './cloud/paths/provision_user.yml'
components:
  schemas:
    OnboardingRequest:
      $ref: './cloud/schemas/OnboardingRequest.yml'
    OnboardingResponse:
      $ref: './cloud/schemas/OnboardingResponse.yml'
    ProvisionRequest:
      $ref: './cloud/schemas/ProvisionRequest.yml'
    ProvisionUserRequest:
      $ref: './cloud/schemas/ProvisionUserRequest.yml'
    ProvisionUserResponse:
      $ref: './cloud/schemas/ProvisionUserResponse.yml'
    ProvisionResponse:
      $ref: './cloud/schemas/ProvisionResponse.yml'
    InvalidRequestError:
      $ref: './cloud/schemas/InvalidRequestError.yml'
    UnauthorizedRequestError:
      $ref: './cloud/schemas/UnauthorizedRequestError.yml'
    ForbiddenRequestError:
      $ref: './cloud/schemas/ForbiddenRequestError.yml'
    Error:
      $ref: './common/schemas/Error.yml'
    OAuthClientConfig:
      $ref: './cloud/schemas/OAuthClientConfig.yml'
    Identity:
      $ref: './cloud/schemas/Identity.yml'
    IdentityWithLinks:
      $ref: './cloud/schemas/IdentityWithLinks.yml'
    LimitEvent:
      $ref: './cloud/schemas/LimitEvent.yml'
    LimitEvents:
      $ref: './cloud/schemas/LimitEvents.yml'
    LimitStatuses:
      $ref: './cloud/schemas/LimitStatuses.yml'
    LimitStatus:
      $ref: './cloud/schemas/LimitStatus.yml'
    Limit:
      $ref: './cloud/schemas/Limit.yml'
    OrgSettings:
      $ref: './cloud/schemas/OrgSettings.yml'
    OrgSetting:
      $ref: './cloud/schemas/OrgSetting.yml'
    Link:
      $ref: './common/schemas/Link.yml'
    Links:
      $ref: './common/schemas/Links.yml'
    OrganizationRequest:
      $ref: './cloud/schemas/OrganizationRequest.yml'
    BucketLimits:
      $ref: "./quartz/schemas/BucketLimits.yml"
    CheckLimits:
      $ref: "./quartz/schemas/CheckLimits.yml"
    DashboardLimits:
      $ref: "./quartz/schemas/DashboardLimits.yml"
    NotificationEndpointLimits:
      $ref: "./quartz/schemas/NotificationEndpointLimits.yml"
    NotificationRuleLimits:
      $ref: "./quartz/schemas/NotificationRuleLimits.yml"
    OrganizationWithToken:
      $ref: "./quartz/schemas/OrganizationWithToken.yml"
    Organization:
      $ref: "./quartz/schemas/Organization.yml"
    Organizations:
      $ref: "./quartz/schemas/Organizations.yml"
    OrgLimits:
      $ref: "./quartz/schemas/OrgLimits.yml"
    RateLimits:
      $ref: "./quartz/schemas/RateLimits.yml"
    RestrictedLimit:
      $ref: "./quartz/schemas/RestrictedLimit.yml"
    TaskLimits:
      $ref: "./quartz/schemas/TaskLimits.yml"
    Unlimited:
      $ref: "./quartz/schemas/Unlimited.yml"
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
