openapi: '3.0.0'
info:
  title: InfluxDB Cloud API Service
  version: 2.0.1
  description: |
    The InfluxDB v2 API provides a programmatic interface for all interactions with InfluxDB. Access the InfluxDB API using the `/api/v2/` endpoint.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /api/v2
#REF_CLOUD_TAGS
#REF_CLOUD_TAG_GROUPS
paths:
#REF_COMMON_PATHS
  /users:
    $ref: './cloud/paths/users.yml'
  '/users/{userID}':
    $ref: './cloud/paths/users_userID.yml'
  /setup:
    $ref: './cloud/paths/setup.yml'
  /setup/user:
    $ref: './cloud/paths/setup_user.yml'
  /authorizations:
    $ref: './cloud/paths/authorizations.yml'
  /authorizations/{authID}:
    $ref: './cloud/paths/authorizations_authID.yml'
  /variables:
    $ref: './cloud/paths/variables.yml'
  '/variables/{variableID}':
    $ref: './cloud/paths/variables_variableID.yml'
  /buckets/{bucketID}/schema/measurements:
    $ref: './cloud/paths/measurements.yml'
  /buckets/{bucketID}/schema/measurements/{measurementID}:
    $ref: './cloud/paths/measurements_measurementID.yml'
  /orgs/{orgID}/limits:
    $ref: './cloud/paths/orgs_orgID_limits_get.yml'
  /orgs/{orgID}/usage:
    $ref: './cloud/paths/orgs_orgID_usage.yml'
  /dashboards:
    $ref: './cloud/paths/dashboards.yml'
  /tasks:
    $ref: './cloud/paths/tasks.yml'
  /tasks/{taskID}:
    $ref: "./cloud/paths/tasks_taskID.yml"
components:
  examples:
    TaskWithFluxRequest:
      $ref: "./common/requestBody/examples/TaskRequestExamples.yml#/TaskWithFluxRequest"
    TaskWithScriptRequest:
      $ref: "./common/requestBody/examples/TaskRequestExamples.yml#/TaskWithScriptRequest"
  parameters:
  #REF_COMMON_PARAMETERS
  schemas:
    #REF_COMMON_SCHEMAS
    AuthorizationPostRequest:
      $ref: './common/schemas/AuthorizationPostRequest.yml'
    Permission:
      $ref: './common/schemas/Permission.yml'
    Resource:
      $ref: './common/schemas/Resource.yml'
    User:
      $ref: './cloud/schemas/User.yml'
    Users:
      $ref: './cloud/schemas/Users.yml'
    OnboardingRequest:
      $ref: './cloud/schemas/OnboardingRequest.yml'
    OnboardingResponse:
      $ref: './cloud/schemas/OnboardingResponse.yml'
    Limit:
      $ref: './cloud/schemas/Limit.yml'
    Variable:
      $ref: './cloud/schemas/Variable.yml'
    Variables:
      $ref: './cloud/schemas/Variables.yml'
    ColumnDataType:
      $ref: './cloud/schemas/ColumnDataType.yml'
    ColumnSemanticType:
      $ref: './cloud/schemas/ColumnSemanticType.yml'
    MeasurementSchema:
      $ref: './cloud/schemas/MeasurementSchema.yml'
    MeasurementSchemaColumn:
      $ref: './cloud/schemas/MeasurementSchemaColumn.yml'
    MeasurementSchemaCreateRequest:
      $ref: './cloud/schemas/MeasurementSchemaCreateRequest.yml'
    MeasurementSchemaList:
      $ref: './cloud/schemas/MeasurementSchemaList.yml'
    MeasurementSchemaUpdateRequest:
      $ref: './cloud/schemas/MeasurementSchemaUpdateRequest.yml'
    Tasks:
      $ref: "./cloud/schemas/Tasks.yml"
    Task:
      $ref: "./cloud/schemas/Task.yml"
    TaskUpdateRequest:
      $ref: "./cloud/schemas/TaskUpdateRequest.yml"
    TaskWithScriptCreateRequest:
      $ref: "./cloud/schemas/TaskWithScriptCreateRequest.yml"
  responses:
    #REF_COMMON_RESPONSES
  securitySchemes:
    TokenAuthentication:
      type: apiKey
      name: Authorization
      in: header
      description: |
        Use the [Token authentication](#section/Authentication/TokenAuthentication)
        scheme to authenticate to the InfluxDB API.

        In your API requests, send an `Authorization` header.
        For the header value, provide the word `Token` followed by a space and an InfluxDB API token.
        The word `Token` is case-sensitive.

        ### Syntax

        `Authorization: Token INFLUX_API_TOKEN`

        For more information and examples, see the following:

        - [`/authorizations`(#tag/Authorizations) endpoints]
        - [Authorize API requests]({{% INFLUXDB_DOCS_URL %}}/api-guide/api_intro/#authentication)
        - [Manage API tokens]({{% INFLUXDB_DOCS_URL %}}/security/tokens/)
    BasicAuthentication:
      type: http
      scheme: basic
      description: |
       ### Basic authentication scheme

       Use the HTTP Basic authentication scheme for InfluxDB `/api/v2` API operations that support it:

       - **username**: InfluxDB Cloud username
       - **password**: InfluxDB Cloud API token

       #### Example

       ```sh
       curl --get "https://europe-west1-1.gcp.cloud2.influxdata.com/query"
             --user "exampleuser@influxdata.com":"INFLUX_API_TOKEN"
       ```

       Replace the following:

       - *`exampleuser@influxdata.com`*: the email address that you signed up with
       - *`INFLUX_API_TOKEN`*: your [InfluxDB API token]({{% INFLUXDB_DOCS_URL %}}/reference/glossary/#token)
security:
  - TokenAuthentication: []
