openapi: "3.0.0"
info:
  title: Influx Cloud API Service
  version: 2.0.1
servers:
  - url: /api/v2
paths:
  REF_COMMON_PATHS
  /users:
    $ref: "./cloud/paths/users.yml"
  "/users/{userID}":
    $ref: "./cloud/paths/users_userID.yml"
  /setup:
    $ref: "./cloud/paths/setup.yml"
  /setup/user:
    $ref: "./cloud/paths/setup_user.yml"
  /authorizations:
    $ref: "./cloud/paths/authorizations.yml"
  /authorizations/{authID}:
    $ref: "./cloud/paths/authorizations_authID.yml"
  /variables:
    $ref: "./cloud/paths/variables.yml"
  "/variables/{variableID}":
    $ref: "./cloud/paths/variables_variableID.yml"
components:
  parameters:
REF_COMMON_PARAMETERS
  schemas:
REF_COMMON_SCHEMAS
    Resource:
      $ref: "./cloud/schemas/Resource.yml"
    Permission:
      $ref: "./cloud/schemas/Permission.yml"
    Authorization:
      $ref: "./cloud/schemas/Authorization.yml"
    Authorizations:
      $ref: "./cloud/schemas/Authorizations.yml"
    User:
      $ref: "./cloud/schemas/User.yml"
    Users:
      $ref: "./cloud/schemas/Users.yml"
    OnboardingRequest:
      $ref: "./cloud/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./cloud/schemas/OnboardingResponse.yml"
    Limit:
      $ref: "./cloud/schemas/Limit.yml"
    Variable:
      $ref: "./cloud/schemas/Variable.yml"
    Variables:
      $ref: "./cloud/schemas/Variables.yml"
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
