openapi: "3.0.0"
info:
  title: IDPE-exclusive API endpoints
  version: 2.0.0
servers:
  - url: /api/v2private
paths:
  /oauth/clientConfig:
    $ref: "./cloud/paths/oauth_clientConfig.yml"                
  /limitevents:
    $ref: "./cloud/paths/limitevents.yml"                
  /orgs/{orgID}/limits:
    $ref: "./cloud/paths/orgs_orgID_limits.yml"                
  /orgs/{orgID}/limits/status:
    $ref: "./cloud/paths/orgs_orgID_limits_status.yml"                
  /orgs/{orgID}/settings:
    $ref: "./cloud/paths/orgs_orgID_settings.yml"                
  /tenants:
    $ref: "./cloud/paths/tenants.yml"                
  /setup/user:
    $ref: "./cloud/paths/setup_user.yml"
components:
  schemas:
    OnboardingRequest:
      $ref: "./cloud/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./cloud/schemas/OnboardingResponse.yml"
    InvalidRequestError:
      $ref: "./cloud/schemas/InvalidRequestError.yml"
    UnauthorizedRequestError:
      $ref: "./cloud/schemas/UnauthorizedRequestError.yml"
    ForbiddenRequestError:
      $ref: "./cloud/schemas/ForbiddenRequestError.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
    OAuthClientConfig:
      $ref: "./cloud/schemas/OAuthClientConfig.yml"
    LimitEvent:
      $ref: "./cloud/schemas/LimitEvent.yml"
    LimitEvents:
      $ref: "./cloud/schemas/LimitEvents.yml"
    LimitStatuses:
      $ref: "./cloud/schemas/LimitStatuses.yml"
    LimitStatus:
      $ref: "./cloud/schemas/LimitStatus.yml"
    Limit:
      $ref: "./cloud/schemas/Limit.yml"
    OrgSettings:
      $ref: "./cloud/schemas/OrgSettings.yml"
    OrgSetting:
      $ref: "./cloud/schemas/OrgSetting.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    OrganizationRequest:
      $ref: "./cloud/schemas/OrganizationRequest.yml"
