openapi: "3.0.0"
info:
  title: IDPE-exclusive API endpoints
  version: 2.3.3
servers:
  - description: |-
      V2 Private is not necessarily private in the sense that the world cannot view it,
      but defines routes that are of little use to the world (quartz-specific routes that
      require a super token (`/setup/user`)), or routes that are not yet guaranteed to
      not change.
  - url: /api/v2private
paths:
  /oauth/clientConfig:
    $ref: "./cloud/paths/oauth_clientConfig.yml"                
  /limitevents:
    $ref: "./cloud/paths/limitevents.yml"                
  /orgs/{orgID}/limits:
    $ref: "./cloud/paths/orgs_orgID_limits.yml"                
  /orgs/{orgID}/limits/status:
    $ref: "./cloud/paths/orgs_orgID_limits_status.yml"                
  /orgs/{orgID}/settings:
    $ref: "./cloud/paths/orgs_orgID_settings.yml"                
  /tenants:
    $ref: "./cloud/paths/tenants.yml"                
  /setup/user:
    $ref: "./cloud/paths/setup_user.yml"
  # annotationd
  /annotations:
    $ref: "./svc/annotationd/paths/annotations.yml"
  /annotations/{annotationID}:
    $ref: "./svc/annotationd/paths/annotation.yml"
  /streams:
    $ref: "./svc/annotationd/paths/streams.yml"
  /streams/{streamID}:
    $ref: "./svc/annotationd/paths/stream.yml"
  # mapsd
  /mapToken:
    $ref: "./svc/mapsd/paths/mapToken.yml"
  # flowd
  /flows/orgs/{orgID}/flows:
    $ref: "./svc/flowd/paths/flows_orgs_orgID_flows.yml"
  /flows/orgs/{orgID}/flows/{id}:
    $ref: "./svc/flowd/paths/flows_orgs_orgID_flows_id.yml"
components:
  schemas:
    OnboardingRequest:
      $ref: "./cloud/schemas/OnboardingRequest.yml"
    OnboardingResponse:
      $ref: "./cloud/schemas/OnboardingResponse.yml"
    InvalidRequestError:
      $ref: "./cloud/schemas/InvalidRequestError.yml"
    UnauthorizedRequestError:
      $ref: "./cloud/schemas/UnauthorizedRequestError.yml"
    ForbiddenRequestError:
      $ref: "./cloud/schemas/ForbiddenRequestError.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
    OAuthClientConfig:
      $ref: "./cloud/schemas/OAuthClientConfig.yml"
    LimitEvent:
      $ref: "./cloud/schemas/LimitEvent.yml"
    LimitEvents:
      $ref: "./cloud/schemas/LimitEvents.yml"
    LimitStatuses:
      $ref: "./cloud/schemas/LimitStatuses.yml"
    LimitStatus:
      $ref: "./cloud/schemas/LimitStatus.yml"
    Limit:
      $ref: "./cloud/schemas/Limit.yml"
    OrgSettings:
      $ref: "./cloud/schemas/OrgSettings.yml"
    OrgSetting:
      $ref: "./cloud/schemas/OrgSetting.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    OrganizationRequest:
      $ref: "./cloud/schemas/OrganizationRequest.yml"
    # annotationd
    AnnotationListFilter:
      $ref: "./svc/annotationd/schemas/AnnotationListFilter.yml"
    AnnotationDeleteFilter:
      $ref: "./svc/annotationd/schemas/AnnotationDeleteFilter.yml"
    BasicFilter:
      $ref: "./svc/annotationd/schemas/BasicFilter.yml"
    AnnotationList:
      $ref: "./svc/annotationd/schemas/AnnotationList.yml"
    AnnotationEventList:
      $ref: "./svc/annotationd/schemas/AnnotationEventList.yml"
    AnnotationEvent:
      $ref: "./svc/annotationd/schemas/AnnotationEvent.yml"
    Annotation:
      $ref: "./svc/annotationd/schemas/Annotation.yml"
    StreamListFilter:
      $ref: "./svc/annotationd/schemas/StreamListFilter.yml"
    StreamDeleteFilter:
      $ref: "./svc/annotationd/schemas/StreamDeleteFilter.yml"
    StreamList:
      $ref: "./svc/annotationd/schemas/StreamList.yml"
    Stream:
      $ref: "./svc/annotationd/schemas/Stream.yml"
    ReadStream:
      $ref: "./svc/annotationd/schemas/ReadStream.yml"
    # mapsd
    Token:
      $ref: "./svc/mapsd/schemas/Token.yml"
    # flowd
    ProtobufAny:
      $ref: "./svc/flowd/schemas/ProtobufAny.yml"
    RuntimeError:
      $ref: "./svc/flowd/schemas/RuntimeError.yml"
    Flow:
      $ref: "./svc/flowd/schemas/Flow.yml"
    FlowCreateRequest:
      $ref: "./svc/flowd/schemas/FlowCreateRequest.yml"
    FlowList:
      $ref: "./svc/flowd/schemas/FlowList.yml"
    FlowUpdateRequest:
      $ref: "./svc/flowd/schemas/FlowUpdateRequest.yml"
  parameters:
    # annotationd
    AnnotationListFilter:
      $ref: "./svc/annotationd/parameters/AnnotationListFilter.yml"
    AnnotationDeleteFilter:
      $ref: "./svc/annotationd/parameters/AnnotationDeleteFilter.yml"
    StreamListFilter:
      $ref: "./svc/annotationd/parameters/StreamListFilter.yml"
    StreamDeleteFilter:
      $ref: "./svc/annotationd/parameters/StreamDeleteFilter.yml"
  responses:
    # annotationd
    NoContent:
      $ref: "./common/responses/NoContent.yml"
    BadRequest:
      $ref: "./common/responses/BadRequest.yml"
    Unauthorized:
      $ref: "./common/responses/Unauthorized.yml"
    NotAllowed:
      $ref: "./common/responses/NotAllowed.yml"
    ServerError:
      $ref: "./common/responses/ServerError.yml"
