openapi: "3.0.0"
info:
  title: Influx Common API
  version: 2.0.1
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /api/v2
paths:
#REF_COMMON_PATHS
components:
  parameters:
#REF_COMMON_PARAMETERS
  schemas:
#REF_COMMON_SCHEMAS
  responses:
#REF_COMMON_RESPONSES
