openapi: "3.0.0"
info:
  title: Influx Legacy API
  version: 2.0.1
servers:
  - url: ""
paths:
  /query:
    $ref: "./legacy/paths/query.yml"
  /write:
    $ref: "./legacy/paths/write.yml"
  /legacy/authorizations:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations.yml"
  /legacy/authorizations/{authID}:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations_authID.yml"
  /legacy/authorizations/{authID}/password:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations_authID_password.yml"
components:
  parameters:
    TraceSpan:
      $ref: "./common/parameters/TraceSpan.yml"
  schemas:
    LegacyAuthorizationPostRequest:
      $ref: "./legacy/schemas/LegacyAuthorizationPostRequest.yml"
    InfluxqlJsonResponse:
      $ref: "./legacy/schemas/InfluxqlJsonResponse.yml"
    InfluxqlCsvResponse:
      $ref: "./legacy/schemas/InfluxqlCsvResponse.yml"
    Authorization:
      $ref: "./common/schemas/Authorization.yml"
    AuthorizationUpdateRequest:
      $ref: "./common/schemas/AuthorizationUpdateRequest.yml"
    Permission:
      $ref: "./common/schemas/Permission.yml"
    Links:
      $ref: "./common/schemas/Links.yml"
    Link:
      $ref: "./common/schemas/Link.yml"
    LineProtocolError:
      $ref: "./common/schemas/LineProtocolError.yml"
    LineProtocolLengthError:
      $ref: "./common/schemas/LineProtocolLengthError.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
    ErrorCode:
      $ref: "./common/schemas/ErrorCode.yml"
  responses:
    ServerError:
      $ref: "./common/responses/ServerError.yml"
