openapi: "3.0.0"
info:
  title: Influx Legacy API
  version: 2.0.1
servers:
  - url: ""
paths:
  /query:
    $ref: "./legacy/paths/query.yml"
  /legacy/authorizations:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations.yml"
  /legacy/authorizations/{authID}:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations_authID.yml"
  /legacy/authorizations/{authID}/password:
    servers:
      - url: "/private"
    $ref: "./legacy/paths/legacy_authorizations_authID_password.yml"
components:
  schemas:
    LegacyAuthorizationPostRequest:
      $ref: "./legacy/schemas/LegacyAuthorizationPostRequest.yml"
    InfluxqlJsonResponse:
      $ref: "./legacy/schemas/InfluxqlJsonResponse.yml"
    InfluxqlCsvResponse:
      $ref: "./legacy/schemas/InfluxqlCsvResponse.yml"
  responses:
    ServerError:
      $ref: "./common/responses/ServerError.yml"
