openapi: '3.0.0'
info:
  title: InfluxData Invokable Scripts Internal API
  version: 0.1.0
  description: |
      Internal API endpoints for Invokable Scripts.
      These operations can only be called internally from other services.
servers:
  - url: '/'
paths:
  '/scripts/labels/update':
    $ref: './svc/invocable-scripts-internal/paths/scripts_labels_update.yml'
  '/scripts/labels/remove':
    $ref: './svc/invocable-scripts-internal/paths/scripts_labels_remove.yml'
components:
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
    AuthorizationError:
      $ref: './common/responses/AuthorizationError.yml'
    InternalServerError:
      $ref: './common/responses/InternalServerError.yml'
  schemas:
    Error:
      $ref: './common/schemas/Error.yml'
    ScriptBulkUpdateLabelRequest:
      $ref: './svc/invocable-scripts-internal/schemas/ScriptBulkUpdateLabelRequest.yml'
    ScriptBulkRemoveLabelRequest:
      $ref: './svc/invocable-scripts-internal/schemas/ScriptBulkRemoveLabelRequest.yml'
