openapi: '3.0.0'
info:
  title: InfluxData Invocable Scripts API
  version: 0.1.0
  description: |
    Manage and execute scripts in InfluxDB.
    An API Invocable Script assigns your custom Flux script to a new InfluxDB API endpoint for your organization.
    Invocable scripts let you execute your script with an HTTP request to the endpoint.
    You can reference parameters in your script as `params.myparameter`.
    When you invoke your script, InfluxDB substitutes your `params` references with key-value pairs that you send in the `params` object.

    For more information and examples, see [Invoke custom scripts](https://docs.influxdata.com/influxdb/cloud/api-guide/api-invocable-scripts).
servers:
  - url: '/'
paths:
  '/scripts':
    $ref: './svc/invocable-scripts/paths/scripts.yml'
  '/scripts/{scriptID}':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID.yml'
  '/scripts/{scriptID}/invoke':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID_invoke.yml'
components:
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
  schemas:
    Error:
      $ref: './common/schemas/Error.yml'
    Script:
      $ref: './svc/invocable-scripts/schemas/Script.yml'
    Scripts:
      $ref: './svc/invocable-scripts/schemas/Scripts.yml'
    ScriptCreateRequest:
      $ref: './svc/invocable-scripts/schemas/ScriptCreateRequest.yml'
    ScriptUpdateRequest:
      $ref: './svc/invocable-scripts/schemas/ScriptUpdateRequest.yml'
    ScriptHTTPResponseData:
      $ref: './svc/invocable-scripts/schemas/ScriptHTTPResponseData.yml'
    ScriptInvocationParams:
      $ref: './svc/invocable-scripts/schemas/ScriptInvocationParams.yml'
    ScriptLanguage:
      $ref: './svc/invocable-scripts/schemas/ScriptLanguage.yml'
