openapi: 3.0.0
info:
  title: fluxdocsd
  version: 1.0.0
servers:
  - url: /
paths:
  /fluxdocs:
    $ref: './svc/fluxdocsd/paths/fluxdocs.yml'
  /fluxdocs/{id}:
    $ref: './svc/fluxdocsd/paths/fluxdocs_id.yml'
  '/fluxdocs/search/{searchTerm}':
    $ref: './svc/fluxdocsd/paths/fluxdocs_search_searchTerm.yml'
components:
  requestBodies:
    FluxdocsParams:
      $ref: './svc/fluxdocsd/requestBodies/FluxdocsParams.yml'
  schemas:
    Fluxdocs:
      $ref: './svc/fluxdocsd/schemas/fluxdocs.yml'
    FluxdocsArray:
      $ref: './svc/fluxdocsd/schemas/fluxdocsArray.yml'
    FluxdocsParameters:
      $ref: './svc/fluxdocsd/schemas/fluxdocsParameters.yml'
    Error:
      $ref: './common/schemas/Error.yml'
  responses:
    NoContent:
      $ref: './common/responses/NoContent.yml'
    ServerError:
      $ref: './common/responses/ServerError.yml'
