openapi: 3.0.0
info:
  title: nifid
  version: 1.0.0
servers:
  - url: /
paths:
  /broker/sub:
    $ref: './svc/nifid/paths/broker_sub.yml'
  /broker/sub/{id}:
    $ref: './svc/nifid/paths/broker_sub_id.yml'
  /broker/sub/{id}/status:
    $ref: './svc/nifid/paths/broker_sub_id_status.yml'
components:
  requestBodies:
    SubscriptionParams:
      $ref: './svc/nifid/requestBodies/SubscriptionParams.yml'
  schemas:
    SubscriptionParams:
      $ref: './svc/nifid/schemas/SubscriptionParams.yml'
    Subscription:
      $ref: './svc/nifid/schemas/Subscription.yml'
    SubscriptionArray:
      $ref: './svc/nifid/schemas/SubscriptionArray.yml'
    Subscriptions:
      $ref: './svc/nifid/schemas/Subscriptions.yml'
    Error:
      $ref: './common/schemas/Error.yml'
  responses:
    NoContent:
      $ref: './common/responses/NoContent.yml'
    ServerError:
      $ref: './common/responses/ServerError.yml'
