openapi: '3.0.0'
info:
  title: InfluxData Invokable Scripts API
  version: 0.1.0
  description: |
      Manage and execute scripts as API endpoints in InfluxDB.

      An API Invokable Script assigns your custom Flux script to a new InfluxDB API endpoint for your organization.
      Invokable scripts let you execute your script as an HTTP request to the endpoint.

      Invokable scripts accept parameters. Add parameter references in your script as `params.myparameter`.
      When you `invoke` your script, you send parameters as key-value pairs in the `params` object.
      InfluxDB executes your script with the key-value pairs as arguments and returns the result.

      For more information and examples, see [Invoke custom scripts](https://docs.influxdata.com/influxdb/cloud/api-guide/api-invokable-scripts/).
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: '/'
paths:
  '/scripts':
    $ref: './svc/invocable-scripts/paths/scripts.yml'
  '/scripts/{scriptID}':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID.yml'
  '/scripts/{scriptID}/invoke':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID_invoke.yml'
  '/scripts/{scriptID}/labels/add':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID_add_labels.yml'
  '/scripts/{scriptID}/labels/remove':
    $ref: './svc/invocable-scripts/paths/scripts_scriptID_remove_labels.yml'
components:
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
    AuthorizationError:
      $ref: './common/responses/AuthorizationError.yml'
    InternalServerError:
      $ref: './common/responses/InternalServerError.yml'
  schemas:
    Error:
      $ref: './common/schemas/Error.yml'
    Script:
      $ref: './svc/invocable-scripts/schemas/Script.yml'
    Scripts:
      $ref: './svc/invocable-scripts/schemas/Scripts.yml'
    ScriptCreateRequest:
      $ref: './svc/invocable-scripts/schemas/ScriptCreateRequest.yml'
    ScriptUpdateRequest:
      $ref: './svc/invocable-scripts/schemas/ScriptUpdateRequest.yml'
    ScriptHTTPResponseData:
      $ref: './svc/invocable-scripts/schemas/ScriptHTTPResponseData.yml'
    ScriptInvocationParams:
      $ref: './svc/invocable-scripts/schemas/ScriptInvocationParams.yml'
    ScriptLanguage:
      $ref: './svc/invocable-scripts/schemas/ScriptLanguage.yml'
