openapi: '3.0.0'
info:
  title: Authzd Internal API
  version: 0.1.0
  description: |
      Internal API endpoints for Authzd.
      These operations can only be called internally from other services.
servers:
  - url: '/'
paths:
  '/access/authorize':
    $ref: './svc/authzd/paths/access_authorize.yml'
  '/access/authorize-global':
    $ref: './svc/authzd/paths/access_authorize_global.yml'
components:
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
    AuthorizationError:
      $ref: './common/responses/AuthorizationError.yml'
    InternalServerError:
      $ref: './common/responses/InternalServerError.yml'
  schemas:
    Error:
      $ref: './common/schemas/Error.yml'
    AccessAuthorizeRequest:
      $ref: './svc/authzd/schemas/AccessAuthorizeRequest.yml'
    AccessFilters:
      $ref: './svc/authzd/schemas/AccessFilters.yml'
    DataFilter:
      $ref: './svc/authzd/schemas/DataFilter.yml'
