openapi: '3.0.0'
info:
  title: Influxdata Managed Functions CRUD API
  version: 0.1.0
servers:
  - url: '/api/v2'
paths:
  '/functions':
    $ref: './svc/managed-functions/paths/functions.yml'
  '/functions/trigger':
    $ref: './svc/managed-functions/paths/functions_trigger.yml'
  '/functions/{functionID}':
    $ref: './svc/managed-functions/paths/functions_functionID.yml'
  '/functions/{functionID}/invoke':
    $ref: './svc/managed-functions/paths/functions_functionID_invoke.yml'
  '/functions/{functionID}/runs':
    $ref: './svc/managed-functions/paths/functions_functionID_runs.yml'
  '/functions/{functionID}/runs/{runID}':
    $ref: './svc/managed-functions/paths/functions_functionID_runs_runID.yml'
components:
  responses:
    ServerError:
      $ref: './common/responses/ServerError.yml'
  schemas:
    Error:
      $ref: './common/schemas/Error.yml'
    Function:
      $ref: './svc/managed-functions/schemas/Function.yml'
    Functions:
      $ref: './svc/managed-functions/schemas/Functions.yml'
    FunctionCreateRequest:
      $ref: './svc/managed-functions/schemas/FunctionCreateRequest.yml'
    FunctionUpdateRequest:
      $ref: './svc/managed-functions/schemas/FunctionUpdateRequest.yml'
    FunctionHTTPResponseData:
      $ref: './svc/managed-functions/schemas/FunctionHTTPResponseData.yml'
    FunctionHTTPResponse:
      $ref: './svc/managed-functions/schemas/FunctionHTTPResponse.yml'
    FunctionHTTPResponseNoData:
      $ref: './svc/managed-functions/schemas/FunctionHTTPResponseNoData.yml'
    FunctionRunBase:
      $ref: './svc/managed-functions/schemas/FunctionRunBase.yml'
    FunctionTriggerResponse:
      $ref: './svc/managed-functions/schemas/FunctionTriggerResponse.yml'
    FunctionRun:
      $ref: './svc/managed-functions/schemas/FunctionRun.yml'
    FunctionRuns:
      $ref: './svc/managed-functions/schemas/FunctionRuns.yml'
    FunctionTriggerRequest:
      $ref: './svc/managed-functions/schemas/FunctionTriggerRequest.yml'
    FunctionInvocationParams:
      $ref: './svc/managed-functions/schemas/FunctionInvocationParams.yml'
    FunctionRunLog:
      $ref: './svc/managed-functions/schemas/FunctionRunLog.yml'
    FunctionLanguage:
      $ref: './svc/managed-functions/schemas/FunctionLanguage.yml'
