openapi: 3.0.0
info:
  title: uiproxyd
  version: 1.0.0
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: /
paths:
  /uiproxy/mapToken:
    $ref: "./svc/uiproxyd/paths/mapToken.yml"
  /uiproxy/sfdc-support:
    $ref: "./svc/uiproxyd/paths/sfdcSupport.yml"
  /uiproxy/quartz-login-url:
    $ref: "./svc/uiproxyd/paths/quartzLoginUrl.yml"
components:
  schemas:
    Token:
      $ref: "./svc/uiproxyd/schemas/Token.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
  requestBodies:
    './svc/uiproxyd/requestBodies/SFDCSupportParams.yml'
  responses:
    ServerError:
      $ref: "./common/responses/ServerError.yml"
    AuthorizationError:
      $ref: "./common/responses/AuthorizationError.yml"
    InternalServerError:
      $ref: "./common/responses/InternalServerError.yml"
