openapi: 3.0.0
info:
  title: nifid
  version: 1.0.0
servers:
  - url: /
paths:
  /broker/subs:
    $ref: './svc/nifid/paths/broker_subs.yml'
  /broker/subs/{id}:
    $ref: './svc/nifid/paths/broker_subs_id.yml'
  /broker/subs/{id}/status:
    $ref: './svc/nifid/paths/broker_subs_id_status.yml'
  /broker/subs/statuses:
    $ref: './svc/nifid/paths/broker_subs_status.yml'
components:
  requestBodies:
    SubscriptionParams:
      $ref: './svc/nifid/requestBodies/SubscriptionParams.yml'
    SubscriptionRunStatus:
      $ref: "./svc/nifid/requestBodies/SubscriptionRunStatus.yml"
  schemas:
    JsonSpec:
      $ref: './svc/nifid/schemas/JsonSpec.yml'
    StringObjectParams:
      $ref: './svc/nifid/schemas/StringObject.yml'
    SubscriptionParams:
      $ref: './svc/nifid/schemas/SubscriptionParams.yml'
    Subscription:
      $ref: './svc/nifid/schemas/Subscription.yml'
    SubscriptionArray:
      $ref: './svc/nifid/schemas/SubscriptionArray.yml'
    Subscriptions:
      $ref: './svc/nifid/schemas/Subscriptions.yml'
    SubscriptionStatus:
      $ref: './svc/nifid/schemas/SubscriptionStatus.yml'
    SubscriptionRunStatus:
      $ref: './svc/nifid/schemas/SubscriptionRunStatus.yml'
    Error:
      $ref: './common/schemas/Error.yml'
  responses:
    NoContent:
      $ref: './common/responses/NoContent.yml'
    ServerError:
      $ref: './common/responses/ServerError.yml'
