openapi: 3.0.0
info:
  title: notebooksd
  version: 1.0.0
servers:
  - url: /
paths:
  /flows/orgs/{orgID}/flows:
    $ref: './svc/notebooksd/paths/flows_orgs_orgID_flows.yml'
  /flows/orgs/{orgID}/flows/{id}:
    $ref: './svc/notebooksd/paths/flows_orgs_orgID_flows_id.yml'
  /notebooks:
    $ref: './svc/notebooksd/paths/notebooks.yml'
  /notebooks/{id}:
    $ref: './svc/notebooksd/paths/notebooks_id.yml'
components:
  requestBodies:
    NotebookParams:
      $ref: './svc/notebooksd/requestBodies/NotebookParams.yml'
  schemas:
    NotebookParams:
      $ref: './svc/notebooksd/schemas/NotebookParams.yml'
    Notebook:
      $ref: './svc/notebooksd/schemas/Notebook.yml'
    NotebookArray:
      $ref: './svc/notebooksd/schemas/NotebookArray.yml'
    Notebooks:
      $ref: './svc/notebooksd/schemas/Notebooks.yml'
    Error:
      $ref: "./common/schemas/Error.yml"
  responses:
    NoContent:
      $ref: './common/responses/NoContent.yml'
    BadRequest:
      $ref: './common/responses/BadRequest.yml'
    Unauthorized:
      $ref: './common/responses/Unauthorized.yml'
    NotAllowed:
      $ref: './common/responses/NotAllowed.yml'
    ServerError:
      $ref: './common/responses/ServerError.yml'
