openapi: "3.0.0"
info:
  title: UI Proxy service
  version: 0.1.0
servers:
  - url: /api/v1
paths:
  /mapToken:
    $ref: "./svc/uiproxyd/paths/mapToken.yml"
  /sfdc-support:
    $ref: "./svc/uiproxyd/paths/sfdcSupport.yml"
components:
  schemas:
    Token:
      $ref: "./svc/uiproxyd/schemas/Token.yml"
    Error:
      $ref: "./common/schemas/Error.yml"
  requestBodies:
    './svc/uiproxyd/requestBodies/SFDCSupportParams.yml'
  responses:
    ServerError:
      $ref: "./common/responses/ServerError.yml"
    AuthorizationError:
      $ref: "./common/responses/AuthorizationError.yml"
    InternalServerError:
      $ref: "./common/responses/InternalServerError.yml"
