type: object
properties:
  config:
    type: object
    properties:
      assets-path:
        type: string
      bolt-path:
        type: string
      e2e-testing:
        type: bool
      engine-path:
        type: string
      feature-flags:
        type: object
      flux-log-enabled:
        type: boolean
      http-bind-address:
        type: string
      http-idle-timeout:
        type: integer
        format: int64
      http-read-header-timeout:
        type: integer
        format: int64
      http-read-timeout:
        type: integer
        format: int64
      http-write-timeout:
        type: integer
        format: int64
      influxql-max-select-buckets:
        type: integer
        format: int64
      influxql-max-select-point:
        type: integer
        format: int64
      influxql-max-select-series:
        type: integer
        format: int64
      log-level:
        type: string
      metrics-disabled:
        type: boolean
      nats-max-payload-bytes:
        type: integer
        format: int64
      nats-port:
        type: integer
        format: int64
      no-tasks:
        type: boolean
      pprof-disabled:
        type: boolean
      query-concurrency:
        type: integer
        format: int32
      query-initial-memory-bytes:
        type: integer
        format: int64
      query-max-memory-bytes:
        type: integer
        format: int64
      query-memory-bytes:
        type: integer
        format: int64
      query-queue-size:
        type: integer
        format: int32
      reporting-disabled:
        type: boolean
      secret-store:
        type: string
      session-length:
        type: integer
        format: int64
      session-renew-disabled:
        type: boolean
      sqlite-path:
        type: string
      storage-cache-max-memory-size:
        type: integer
        format: int64
      storage-cache-snapshot-memory-size:
        type: integer
        format: int64
      storage-cache-snapshot-write-cold-duration:
        type: string
      storage-compact-full-write-cold-duration:
        type: string
      storage-compact-throughput-burst:
        type: integer
        format: int64
      storage-max-concurrent-compactions:
        type: integer
        format: int64
      storage-max-index-log-file-size:
        type: integer
        format: int64
      storage-no-validate-field-size:
        type: boolean
      storage-retention-check-interval:
        type: string
      storage-series-file-max-concurrent-snapshot-compactions:
        type: integer
        format: int64
      storage-series-id-set-cache-size:
        type: integer
        format: int64
      storage-shard-precreator-advance-period:
        type: string
      storage-shard-precreator-check-interval:
        type: string
      storage-tsm-use-madv-willneed:
        type: boolean
      storage-validate-keys:
        type: boolean
      storage-wal-fsync-delay:
        type: string
      storage-wal-max-concurrent-writes:
        type: integer
        format: int64
      storage-wal-max-write-delay:
        type: integer
        format: int64
      storage-write-timeout:
        type: integer
        format: int64
      store:
        type: string
      testing-always-allow-setup:
        type: boolean
      tls-cert:
        type: string
      tls-key:
        type: string
      tls-min-version:
        type: string
      tls-strict-ciphers:
        type: boolean
      tracing-type:
        type: string
      ui-disabled:
        type: boolean
      vault-addr:
        type: string
      vault-cacert:
        type: string
      vault-capath:
        type: string
      vault-client-cert:
        type: string
      vault-client-key:
        type: string
      vault-client-timeout:
        type: integer
        format: int64
      vault-max-retries:
        type: integer
        format: int64
      vault-skip-verify:
        type: boolean
      vault-tls-server-name:
        type: string
      vault-token:
        type: string
