# Ideally this would include a full list of config flags, but since these all
# contain dashes and Oats doesn't work with parameters that have dashes, we
# need to leave it as a generic object. See: https://github.com/influxdata/oats/issues/19
type: object
properties:
  config:
    type: object
